server:
  port: "8080"
  mode: "debug"

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "testogo"
  charset: "utf8mb4"
  maxIdleConns: 10
  maxOpenConns: 100

jwt:
  secret: "your-secret-key"
  expire: 24  # hours

upload:
  savePath: "./resource"
  maxSize: 10 # MB
