server:
  port: "8080"
  mode: "debug"

database:
  driver: "mysql"
  host: "10.37.19.94"
  port: 3306
  username: "db_testogo"
  password: "1WVW2GdWgHTfXmnJiiJK"
  dbname: "db_testogo"
  charset: "utf8mb4"
  maxIdleConns: 10
  maxOpenConns: 100

jwt:
  secret: "8nf656Boi0IeWn5MsDIV"
  expire: 72  # hours

upload:
  savePath: "./resource"
  maxSize: 10 # MB
